import { Inter } from "next/font/google";
import "./globals.css";
import Search from "./search";
import Menu from "./menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu/>
        <Search/> 
        {children}</body>
    </html>
  );
}
